import { Testimonial } from "../types";

/**
 * Gabungan reference/rekap-testimoni.md (Prof. lalu Dr.) + testimoni yang sudah ada di situs.
 * Untuk nama yang sama dengan data lama (Leopold, Arif): isi testimoni/peran/avatar mengikuti versi lama.
 */
export const testimonials: Testimonial[] = [
  {
    id: 1,
    quote:
      "Sebagai Guru Besar, saya dituntut terus produktif dalam publikasi. NotebookLM membantu saya menganalisis ratusan paper dan menemukan research gap dengan cepat. Riset yang dulu butuh berminggu-minggu, sekarang bisa selesai dalam hitungan hari.",
    author: "Prof. Dr. Ars. Eko Nursanty, ST., MT.",
    role: "Guru Besar Universitas 17 Agustus 1945 (UNTAG) Semarang",
    avatar: "/images/testimonials/profsanti.avif",
  },
  {
    id: 2,
    quote:
      "Sebagai dosen senior, awalnya saya cukup ragu menggunakan AI dalam aktivitas akademik. Namun setelah mengikuti Kelas Inovatif dari Maret 2025, pandangan saya berubah total. AI—terutama perpaduan antara Cursor & Scipace—ternyata sangat membantu dalam menyusun materi kuliah, menulis buku ajar dan buku referensi, hingga menghasilkan artikel ilmiah. Berkat kelas ini, saya lebih produktif dan berhasil menyelesaikan lebih banyak karya dibanding sebelumnya.",
    author: "Prof. Dr. Ir. Rupa Matheus, M.Si.",
    role: "Guru Besar Politani Kupang, NTT",
    avatar: "/images/testimonials/prof-dr-ir-rupa-matheus-m-si.avif",
  },
  {
    id: 3,
    quote:
      "Alhamdulillah kegiatan Kelas Inovatif ini sangat membantu & memudahkan saya menyelesaikan tugas kegiatan Tri Dharma PT secara luas maupun pelaksanaan Dharma Pendidikan & Pengajaran. NotebookLM yg diajarkan di Kelas Inovatif sangat bermanfaat ketika saya menyiapkan atau membuat Ppt dgn kendala waktu yg sangat terbatas, ppt generated by NotebookLM sangat bagus dibandingkan dgn menggunakan AI yg lain. Saya sarankan pada semua akademisi u mengikuti acara Kelas Inovatif karena saya sudah rasakan manfaatnya. Mari maju dan berkembang bersama Kelas Inovatif",
    author: "Prof. Dr. M. Natsir, SE., M.Si",
    role: "Dosen Universitas Halu Oleo",
    avatar: "/images/testimonials/prof-dr-m-natsir-se-m-si.avif",
  },
  {
    id: 4,
    quote:
      "Puji Tuhan, dengan mengikuti Kelas Inovatif, khususnya kelas intensif Cursor bersama mentor Pak Arianto, disertasi saya berhasil selesai. Skor Turnitin saya waktu itu 11% dan sebenarnya masih bisa lebih rendah lagi dengan bantuan Cursor, karena sangat akurat. Saya dan tim juga sudah membuktikan, artikel yang kami tulis dengan Cursor sudah berhasil tembus Scopus Q1.",
    author: "Dr. Leopold Baginda, S.Pd., M.Th.",
    role: "Alumni Doktoral & Publikasi Scopus",
    avatar: "/images/testimonials/leopold-baginda.avif",
  },
  {
    id: 5,
    quote:
      "Saya udah coba macem-macem tool untuk mengatasi plagiasi. Cuma NotebookLM & Cursor yang bisa konsisten 5% buat standar Scopus.",
    author: "Dr. Tri Nugraha Sakti, MSI",
    role: "Lecturer LSPR Institute",
    avatar: "/images/testimonials/dr-tri-nugraha-sakti-msi.avif",
  },
  {
    id: 6,
    quote:
      "Jujur, saya sangat bersyukur mengenal kelas ini. Pak Arianto sangat sabar membimbing. Saya sudah ikut banyak workshop AI, tapi di Kelas Inovatif jauh lebih simple dan mudah dipraktikkan. Setelah menerapkan trik penulisan buku dari kelas intensif Cursor, alhamdulillah kini 6 buku saya terbit ber-ISBN. Target saya sekarang, setiap bulan menerbitkan satu buku baru.",
    author: "Dr. R. Arif Muljohadi, S.H., M.Hum.",
    role: "Dosen dan Penulis Buku",
    avatar: "/images/testimonials/arif.webp",
  },
  {
    id: 7,
    quote:
      "Fitur presentasi NotebookLM luar biasa. Upload jurnal, langsung jadi slide presentasi yang siap pakai. Persiapan seminar yang biasa 3 hari, sekarang cukup 2 jam.",
    author: "Dr. Mahmud, S.E., M.M.",
    role: "Dosen Universitas Dian Nuswantoro",
    avatar: "/images/testimonials/mahfud.gif",
  },
  {
    id: 8,
    quote:
      "Sebagai Direktur, waktu saya terbatas. NotebookLM bantu saya tetap update literatur terbaru tanpa harus baca satu per satu. Review 50 jurnal? Cukup 1 sore.",
    author: "Dr. Anas Rahmad Hidayat, S.KM., M.Kes.",
    role: "Direktur Poltekkes Permata Indonesia Yogyakarta",
    avatar: "/images/testimonials/anas.gif",
  },
  {
    id: 9,
    quote:
      "Sebagai dosen, saya harus baca puluhan referensi untuk satu mata kuliah. Dengan NotebookLM, saya bisa merangkum dan membandingkan isi jurnal dalam hitungan menit. Produktivitas riset saya meningkat drastis.",
    author: "Dr. Nur Arida Hendrawati, S.IP, MM.",
    role: "Universitas Negeri Yogyakarta",
    avatar: "/images/testimonials/nurarida.avif",
  },
  {
    id: 10,
    quote:
      "Sangat membantu membedah ratusan jurnal dalam waktu singkat. Dulu bingung membangun argumen untuk kajian pustaka, sekarang dengan NotebookLM draf awal selesai dalam hitungan jam.",
    author: "Dr. Leni Zahara, S. Pd., MP",
    role: "Dosen Universitas Negeri Padang",
    avatar: "/images/testimonials/dr-leni-zahara-s-pd-mp.avif",
  },
  {
    id: 11,
    quote:
      "Materi yang diajarkan sangat praktis! Proses mengumpulkan dan mereview banyak jurnal dalam bahasa Inggris jauh lebih cepat dan mudah dipahami.",
    author: "Dr. Esther Hesline Palandi, M.Pd.",
    role: "Dosen Politeknik Negeri Malang",
    avatar: "/images/testimonials/dr-esther-hesline-palandi-m-pd.avif",
  },
  {
    id: 12,
    quote:
      "mengikuti pelatihan/kursus di Klasinovatif sangat menunjang saya dalam pekerjaan saya sebagai pengajar. Materi yang diberikan sangat mengena, pemateri sangat care dan sabar apabila kita minta untuk diulangi lagi materinya, apalagi bagi kami yang sudah berusia, dan gaptek. Ada kepedulian sebagai bonus apabila kita berpartisipasi aktif saat diskusi (dimasukan sebagai bagian dalam jurnal PKM), sangat hebat sekali. Semoga materi2 yang dibagi bisa bermanfaat selanjutnya. Pokoknya top mengikuti Klasinovatif.",
    author: "Dr. Ir. Johanna Taribuka, M.P.",
    role: "Universitas Pattimura Ambon",
    avatar: "/images/testimonials/dr-ir-johanna-taribuka-m-p.avif",
  },
  {
    id: 13,
    quote:
      "Setelah mengikuti program kelas Inovatif, sya banyak mendapat kan ilmu tentang penulisan Jurnal Ilmiah berbasi AI, trmksh banyak atas ilmu yang diberikan..",
    author: "Dr. Ahmad Zayyadi, M.A., M.H.I",
    role: "Dosen UIN Profesor Kiai Haji Saifuddin Zuhri Purwokerto",
    avatar: "/images/testimonials/dr-ahmad-zayyadi-m-a-m-h-i.avif",
  },
  {
    id: 14,
    quote:
      "Terimakasih kelasinovatif yang telah memberikan kesempatan mengikuti event di komunitas kelas inovatif yang luar biasa. Saya benar merasakan manfaatnya dan dapat mengikuti kelas dengan baik meski saya sudah lebih 60 tahun. Karena pengajarnya sangat sabar dan detail cara menjelaskannya. Mas Daffa sebagai operator dan moderator sangat ramah, santun, dan akrab dengan peserta. Sekali lagi terimakasih kelasinovatif. Semoga semakin sukses membantu kami yang ingin selalu belajar. Aamiin YRA 🙌🏼🙏🏼",
    author: "Dr. Dwi Asih Kumala Handayani, M.Pd.",
    role: "Dosen Universitas Ivet Semarang",
    avatar: "/images/testimonials/dr-dwi-asih-kumala-handayani-m-pd.avif",
  },
  {
    id: 15,
    quote:
      "Saya awam dengan AI, namun di Kelas Inovatif saya justru 'tersesat di jalan yang benar'. Di sini, pembelajaran diberikan perlahan dan bertahap. Hasilnya, saya bisa menyelesaikan studi magister saya, dan tahun depan berencana melanjutkan ke jenjang doktoral S3.",
    author: "Wayan Tangun Setiarien, M.M.",
    role: "Alumni Magister Manajemen",
    avatar: "/images/testimonials/wayan-tangun.avif",
  },
  {
    id: 16,
    quote:
      "Saya mahasiswa hukum. Syukurnya, saya bertemu Kelas Inovatif di waktu yang tepat. Dengan bimbingan step by step yang sangat detail, saya berhasil menyusun proposal tesis dengan revisi yang sangat sedikit. Tingkat plagiasi juga rata-rata di bawah 10%. Materinya mudah dipahami, prosesnya jelas dan terstruktur.",
    author: "Akhmad Suhaidi, S.H",
    role: "Mahasiswa Hukum",
    avatar: "/images/testimonials/akhmad-suhaidi.avif",
  },
  {
    id: 17,
    quote:
      "Alhamdulillah, saya berhasil menyelesaikan studi S3 Doktoral dengan predikat Cumlaude. Untuk teman-teman yang sedang dalam proses penulisan disertasi, tetap semangat—kalian pasti bisa! Terima kasih Kelas Inovatif atas support-nya; saya sangat terbantu dalam menelusuri jurnal-jurnal yang dibutuhkan dan menyelesaikan disertasi tepat waktu.",
    author: "Nur Aridha",
    role: "Alumni Doktoral S3",
    avatar: "/images/testimonials/nurarida.avif",
  },
];
