export interface AlumniStory {
    id: string;
    name: string;
    title: string;           // Gelar/afiliasi
    photo: string;           // Path ke gambar
    persona: PersonaType;    // Kategori persona
    personaLabel: string;    // Label untuk ditampilkan
    /** Teks testimoni utuh dari rekap; di kartu dipotong (line-clamp), di modal dipecah ke timeline. */
    quote: string;
    story: {
        before: string;        // Potongan verbatim (biasanya awal testimoni)
        turningPoint: string;  // Potongan verbatim (tengah)
        after: string;         // Potongan verbatim (akhir)
    };
    highlights: string[];    // Frasa singkat yang disadur dari kata-kata rekap (bukan angka fiksi)
    videoUrl?: string;       // YouTube URL (opsional)
}

export type PersonaType =
    | 'awam-teknologi'
    | 'stuck-lama'
    | 'takut-plagiasi'
    | 'mahasiswa-biasa'
    | 'produktif-menulis'
    | 'dosen-muda';

/** 14 cerita — sumber teks: reference/rekap-testimoni.md (urutan: Prof. lalu Dr.). */
export const stories: AlumniStory[] = [
    {
        id: 'eko-nursanty',
        name: 'Prof. Dr. Ars. Eko Nursanty, ST., MT.',
        title: 'Guru Besar Universitas 17 Agustus 1945 (UNTAG) Semarang',
        photo: '/images/testimonials/profsanti.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Guru Besar & Publikasi',
        quote:
            'Sebagai Guru Besar, saya dituntut terus produktif dalam publikasi. NotebookLM membantu saya menganalisis ratusan paper dan menemukan research gap dengan cepat. Riset yang dulu butuh berminggu-minggu, sekarang bisa selesai dalam hitungan hari.',
        story: {
            before: 'Sebagai Guru Besar, saya dituntut terus produktif dalam publikasi.',
            turningPoint:
                'NotebookLM membantu saya menganalisis ratusan paper dan menemukan research gap dengan cepat.',
            after: 'Riset yang dulu butuh berminggu-minggu, sekarang bisa selesai dalam hitungan hari.'
        },
        highlights: ['NotebookLM', 'Ratusan paper', 'Hitungan hari'],
        videoUrl: ''
    },
    {
        id: 'rupa-matheus',
        name: 'Prof. Dr. Ir. Rupa Matheus, M.Si.',
        title: 'Guru Besar Politani Kupang, NTT',
        photo: '/images/testimonials/prof-dr-ir-rupa-matheus-m-si.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Guru Besar & Dosen Senior',
        quote:
            'Sebagai dosen senior, awalnya saya cukup ragu menggunakan AI dalam aktivitas akademik. Namun setelah mengikuti Kelas Inovatif dari Maret 2025, pandangan saya berubah total. AI—terutama perpaduan antara Cursor & Scipace—ternyata sangat membantu dalam menyusun materi kuliah, menulis buku ajar dan buku referensi, hingga menghasilkan artikel ilmiah. Berkat kelas ini, saya lebih produktif dan berhasil menyelesaikan lebih banyak karya dibanding sebelumnya.',
        story: {
            before: 'Sebagai dosen senior, awalnya saya cukup ragu menggunakan AI dalam aktivitas akademik.',
            turningPoint:
                'Namun setelah mengikuti Kelas Inovatif dari Maret 2025, pandangan saya berubah total. AI—terutama perpaduan antara Cursor & Scipace—ternyata sangat membantu dalam menyusun materi kuliah, menulis buku ajar dan buku referensi, hingga menghasilkan artikel ilmiah.',
            after: 'Berkat kelas ini, saya lebih produktif dan berhasil menyelesaikan lebih banyak karya dibanding sebelumnya.'
        },
        highlights: ['Kelas Inovatif Maret 2025', 'Cursor & Scipace', 'Lebih banyak karya'],
        videoUrl: ''
    },
    {
        id: 'prof-m-natsir',
        name: 'Prof. Dr. M. Natsir, SE., M.Si',
        title: 'Dosen Universitas Halu Oleo',
        photo: '/images/testimonials/prof-dr-m-natsir-se-m-si.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Tri Dharma & NotebookLM',
        quote:
            'Alhamdulillah kegiatan Kelas Inovatif ini sangat membantu & memudahkan saya menyelesaikan tugas kegiatan Tri Dharma PT secara luas maupun pelaksanaan Dharma Pendidikan & Pengajaran. NotebookLM yg diajarkan di Kelas Inovatif sangat bermanfaat ketika saya menyiapkan atau membuat Ppt dgn kendala waktu yg sangat terbatas, ppt generated by NotebookLM sangat bagus dibandingkan dgn menggunakan AI yg lain. Saya sarankan pada semua akademisi u mengikuti acara Kelas Inovatif karena saya sudah rasakan manfaatnya. Mari maju dan berkembang bersama Kelas Inovatif',
        story: {
            before:
                'Alhamdulillah kegiatan Kelas Inovatif ini sangat membantu & memudahkan saya menyelesaikan tugas kegiatan Tri Dharma PT secara luas maupun pelaksanaan Dharma Pendidikan & Pengajaran.',
            turningPoint:
                'NotebookLM yg diajarkan di Kelas Inovatif sangat bermanfaat ketika saya menyiapkan atau membuat Ppt dgn kendala waktu yg sangat terbatas, ppt generated by NotebookLM sangat bagus dibandingkan dgn menggunakan AI yg lain.',
            after: 'Saya sarankan pada semua akademisi u mengikuti acara Kelas Inovatif karena saya sudah rasakan manfaatnya. Mari maju dan berkembang bersama Kelas Inovatif'
        },
        highlights: ['Tri Dharma', 'NotebookLM untuk PPT', 'Berkembang bersama Kelas Inovatif'],
        videoUrl: ''
    },
    {
        id: 'leopold-baginda',
        name: 'Dr. Leopold Baginda, S.Pd., M.Th.',
        title: 'Dosen STT Injili Indonesia Palu',
        photo: '/images/testimonials/leopold-baginda.avif',
        persona: 'stuck-lama',
        personaLabel: 'Disertasi & Integritas',
        quote:
            "Disertasi itu perjalanan sepi. Tapi dengan 'teman diskusi' yang tepat, Turnitin saya bisa turun ke 7% dan tembus Scopus Q1.",
        story: {
            before: 'Disertasi itu perjalanan sepi.',
            turningPoint:
                "Tapi dengan 'teman diskusi' yang tepat, Turnitin saya bisa turun ke 7% dan tembus Scopus Q1.",
            after: ''
        },
        highlights: ['Disertasi', 'Turnitin 7%', 'Scopus Q1'],
        videoUrl: ''
    },
    {
        id: 'tri-nugraha',
        name: 'Dr. Tri Nugraha Sakti, MSI',
        title: 'Lecturer LSPR Institute',
        photo: '/images/testimonials/dr-tri-nugraha-sakti-msi.avif',
        persona: 'takut-plagiasi',
        personaLabel: 'Takut Plagiasi',
        quote:
            'Saya udah coba macem-macem tool untuk mengatasi plagiasi. Cuma NotebookLM & Cursor yang bisa konsisten 5% buat standar Scopus.',
        story: {
            before: 'Saya udah coba macem-macem tool untuk mengatasi plagiasi.',
            turningPoint: 'Cuma NotebookLM & Cursor yang bisa konsisten 5% buat standar Scopus.',
            after: ''
        },
        highlights: ['NotebookLM & Cursor', '5% standar Scopus', 'Plagiasi'],
        videoUrl: ''
    },
    {
        id: 'arif-muljohadi',
        name: 'Dr. R. Arif Muljohadi, S.H., M.Hum.',
        title: 'Dosen Universitas Bangkalan',
        photo: '/images/testimonials/arif.webp',
        persona: 'produktif-menulis',
        personaLabel: 'Produktif Menulis Buku',
        quote:
            "Dulu target 'Satu Bulan Satu Buku' rasanya mustahil. Sekarang? Satu semester ganjil aja jadi 3 buku.",
        story: {
            before: "Dulu target 'Satu Bulan Satu Buku' rasanya mustahil.",
            turningPoint: 'Sekarang? Satu semester ganjil aja jadi 3 buku.',
            after: ''
        },
        highlights: ['Satu Bulan Satu Buku', '3 buku', 'Semester ganjil'],
        videoUrl: ''
    },
    {
        id: 'mahmud',
        name: 'Dr. Mahmud, S.E., M.M.',
        title: 'Dosen Universitas Dian Nuswantoro',
        photo: '/images/testimonials/mahfud.gif',
        persona: 'produktif-menulis',
        personaLabel: 'Presentasi & Seminar',
        quote:
            'Fitur presentasi NotebookLM luar biasa. Upload jurnal, langsung jadi slide presentasi yang siap pakai. Persiapan seminar yang biasa 3 hari, sekarang cukup 2 jam.',
        story: {
            before: 'Fitur presentasi NotebookLM luar biasa.',
            turningPoint: 'Upload jurnal, langsung jadi slide presentasi yang siap pakai.',
            after: 'Persiapan seminar yang biasa 3 hari, sekarang cukup 2 jam.'
        },
        highlights: ['Presentasi NotebookLM', 'Slide siap pakai', '3 hari → 2 jam'],
        videoUrl: ''
    },
    {
        id: 'anas-rahmad-hidayat',
        name: 'Dr. Anas Rahmad Hidayat, S.KM., M.Kes.',
        title: 'Direktur Poltekkes Permata Indonesia Yogyakarta',
        photo: '/images/testimonials/anas.gif',
        persona: 'produktif-menulis',
        personaLabel: 'Pimpinan & Literatur',
        quote:
            'Sebagai Direktur, waktu saya terbatas. NotebookLM bantu saya tetap update literatur terbaru tanpa harus baca satu per satu. Review 50 jurnal? Cukup 1 sore.',
        story: {
            before: 'Sebagai Direktur, waktu saya terbatas.',
            turningPoint:
                'NotebookLM bantu saya tetap update literatur terbaru tanpa harus baca satu per satu.',
            after: 'Review 50 jurnal? Cukup 1 sore.'
        },
        highlights: ['Direktur', '50 jurnal', '1 sore'],
        videoUrl: ''
    },
    {
        id: 'nur-arida-hendrawati',
        name: 'Dr. Nur Arida Hendrawati, S.IP, MM.',
        title: 'Universitas Negeri Yogyakarta',
        photo: '/images/testimonials/nurarida.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Dosen & Riset',
        quote:
            'Sebagai dosen, saya harus baca puluhan referensi untuk satu mata kuliah. Dengan NotebookLM, saya bisa merangkum dan membandingkan isi jurnal dalam hitungan menit. Produktivitas riset saya meningkat drastis.',
        story: {
            before: 'Sebagai dosen, saya harus baca puluhan referensi untuk satu mata kuliah.',
            turningPoint:
                'Dengan NotebookLM, saya bisa merangkum dan membandingkan isi jurnal dalam hitungan menit.',
            after: 'Produktivitas riset saya meningkat drastis.'
        },
        highlights: ['Puluhan referensi', 'Hitungan menit', 'Produktivitas riset'],
        videoUrl: ''
    },
    {
        id: 'leni-zahara',
        name: 'Dr. Leni Zahara, S. Pd., MP',
        title: 'Dosen Universitas Negeri Padang',
        photo: '/images/testimonials/dr-leni-zahara-s-pd-mp.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Kajian Pustaka',
        quote:
            'Sangat membantu membedah ratusan jurnal dalam waktu singkat. Dulu bingung membangun argumen untuk kajian pustaka, sekarang dengan NotebookLM draf awal selesai dalam hitungan jam.',
        story: {
            before: 'Sangat membantu membedah ratusan jurnal dalam waktu singkat.',
            turningPoint: 'Dulu bingung membangun argumen untuk kajian pustaka, sekarang dengan NotebookLM draf awal selesai dalam hitungan jam.',
            after: ''
        },
        highlights: ['Ratusan jurnal', 'NotebookLM', 'Hitungan jam'],
        videoUrl: ''
    },
    {
        id: 'esther-hesline-palandi',
        name: 'Dr. Esther Hesline Palandi, M.Pd.',
        title: 'Dosen Politeknik Negeri Malang',
        photo: '/images/testimonials/dr-esther-hesline-palandi-m-pd.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Review Jurnal',
        quote:
            'Materi yang diajarkan sangat praktis! Proses mengumpulkan dan mereview banyak jurnal dalam bahasa Inggris jauh lebih cepat dan mudah dipahami.',
        story: {
            before: 'Materi yang diajarkan sangat praktis!',
            turningPoint:
                'Proses mengumpulkan dan mereview banyak jurnal dalam bahasa Inggris jauh lebih cepat dan mudah dipahami.',
            after: ''
        },
        highlights: ['Materi praktis', 'Jurnal bahasa Inggris', 'Lebih cepat'],
        videoUrl: ''
    },
    {
        id: 'johanna-taribuka',
        name: 'Dr. Ir. Johanna Taribuka, M.P.',
        title: 'Universitas Pattimura Ambon',
        photo: '/images/testimonials/dr-ir-johanna-taribuka-m-p.avif',
        persona: 'awam-teknologi',
        personaLabel: 'Pelatihan Klasinovatif',
        quote:
            'mengikuti pelatihan/kursus di Klasinovatif sangat menunjang saya dalam pekerjaan saya sebagai pengajar. Materi yang diberikan sangat mengena, pemateri sangat care dan sabar apabila kita minta untuk diulangi lagi materinya, apalagi bagi kami yang sudah berusia, dan gaptek. Ada kepedulian sebagai bonus apabila kita berpartisipasi aktif saat diskusi (dimasukan sebagai bagian dalam jurnal PKM), sangat hebat sekali. Semoga materi2 yang dibagi bisa bermanfaat selanjutnya. Pokoknya top mengikuti Klasinovatif.',
        story: {
            before:
                'mengikuti pelatihan/kursus di Klasinovatif sangat menunjang saya dalam pekerjaan saya sebagai pengajar. Materi yang diberikan sangat mengena, pemateri sangat care dan sabar apabila kita minta untuk diulangi lagi materinya, apalagi bagi kami yang sudah berusia, dan gaptek.',
            turningPoint:
                'Ada kepedulian sebagai bonus apabila kita berpartisipasi aktif saat diskusi (dimasukan sebagai bagian dalam jurnal PKM), sangat hebat sekali.',
            after: 'Semoga materi2 yang dibagi bisa bermanfaat selanjutnya. Pokoknya top mengikuti Klasinovatif.'
        },
        highlights: ['Klasinovatif', 'Pemateri sabar', 'Jurnal PKM'],
        videoUrl: ''
    },
    {
        id: 'ahmad-zayyadi',
        name: 'Dr. Ahmad Zayyadi, M.A., M.H.I',
        title: 'Dosen UIN Profesor Kiai Haji Saifuddin Zuhri Purwokerto',
        photo: '/images/testimonials/dr-ahmad-zayyadi-m-a-m-h-i.avif',
        persona: 'produktif-menulis',
        personaLabel: 'Jurnal Ilmiah & AI',
        quote:
            'Setelah mengikuti program kelas Inovatif, sya banyak mendapat kan ilmu tentang penulisan Jurnal Ilmiah berbasi AI, trmksh banyak atas ilmu yang diberikan..',
        story: {
            before:
                'Setelah mengikuti program kelas Inovatif, sya banyak mendapat kan ilmu tentang penulisan Jurnal Ilmiah berbasi AI, trmksh banyak atas ilmu yang diberikan..',
            turningPoint: '',
            after: ''
        },
        highlights: ['Jurnal Ilmiah berbasis AI', 'Kelas Inovatif', 'Ilmu yang diberikan'],
        videoUrl: ''
    },
    {
        id: 'dwi-asih-kumala-handayani',
        name: 'Dr. Dwi Asih Kumala Handayani, M.Pd.',
        title: 'Dosen Universitas Ivet Semarang',
        photo: '/images/testimonials/dr-dwi-asih-kumala-handayani-m-pd.avif',
        persona: 'awam-teknologi',
        personaLabel: 'Komunitas Kelas Inovatif',
        quote:
            'Terimakasih kelasinovatif yang telah memberikan kesempatan mengikuti event di komunitas kelas inovatif yang luar biasa. Saya benar merasakan manfaatnya dan dapat mengikuti kelas dengan baik meski saya sudah lebih 60 tahun. Karena pengajarnya sangat sabar dan detail cara menjelaskannya. Mas Daffa sebagai operator dan moderator sangat ramah, santun, dan akrab dengan peserta. Sekali lagi terimakasih kelasinovatif. Semoga semakin sukses membantu kami yang ingin selalu belajar. Aamiin YRA 🙌🏼🙏🏼',
        story: {
            before:
                'Terimakasih kelasinovatif yang telah memberikan kesempatan mengikuti event di komunitas kelas inovatif yang luar biasa. Saya benar merasakan manfaatnya dan dapat mengikuti kelas dengan baik meski saya sudah lebih 60 tahun.',
            turningPoint:
                'Karena pengajarnya sangat sabar dan detail cara menjelaskannya. Mas Daffa sebagai operator dan moderator sangat ramah, santun, dan akrab dengan peserta.',
            after: 'Sekali lagi terimakasih kelasinovatif. Semoga semakin sukses membantu kami yang ingin selalu belajar. Aamiin YRA 🙌🏼🙏🏼'
        },
        highlights: ['Komunitas kelasinovatif', 'Lebih 60 tahun', 'Mas Daffa'],
        videoUrl: ''
    }
];
